package iconspec

import (
	"fmt"
	"strings"
)

// ComposeSVG renders the spec to an SVG document.
//
// Structure, painted back to front:
//
//	tile gradient rect  ->  hairline border  ->  motif group  ->  layer paths
//
// Text is emitted as PATHS, never <text>: an icon must render identically on
// machines that do not have the font installed, which is all of them.
func (s *Spec) ComposeSVG() (string, error) {
	var b strings.Builder

	stops := s.Palette.resolvedStops()
	var heroStops strings.Builder
	for _, st := range stops {
		fmt.Fprintf(&heroStops, `<stop offset="%g" stop-color="%s"/>`, *st.Offset, st.Color)
	}

	inset := s.TileInset
	side := s.ViewBox - 2*inset

	fmt.Fprintf(&b, `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by frameworks/go/cmd/gen-icon — do not edit by hand. -->
<svg width="%g" height="%g" viewBox="0 0 %g %g" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="tile" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="%s"/><stop offset="1" stop-color="%s"/></linearGradient>
    <linearGradient id="hero" x1="0" y1="0" x2="0.4" y2="1">%s</linearGradient>
  </defs>
  <rect x="%g" y="%g" width="%g" height="%g" rx="%g" fill="url(#tile)"/>
`,
		s.ViewBox, s.ViewBox, s.ViewBox, s.ViewBox,
		s.Palette.TileTop, s.Palette.TileBottom,
		heroStops.String(),
		inset, inset, side, side, s.TileRadius)

	// The border is inset by half a stroke width so the 1px hairline lands
	// INSIDE the tile rather than straddling its edge, where the corner mask
	// would clip half of it away.
	if s.Palette.Border != "" {
		fmt.Fprintf(&b,
			`  <rect x="%g" y="%g" width="%g" height="%g" rx="%g" fill="none" stroke="%s" stroke-width="1"/>`+"\n",
			inset+0.5, inset+0.5, side-1, side-1, s.TileRadius-0.5, s.Palette.Border)
	}

	if s.Motif != nil && strings.TrimSpace(s.Motif.SVG) != "" {
		// "hero" resolves to the gradient, exactly as it does for a layer.
		// textloom's motif is dim background texture and wants a flat tone, but
		// an app whose artwork IS the subject (voicelab' speech bubble) needs
		// the same gradient its wordmark uses — otherwise the two halves of one
		// icon are painted from different palettes.
		motifFill := s.Motif.Color
		if motifFill == "hero" {
			motifFill = "url(#hero)"
		}
		fmt.Fprintf(&b, `  <g opacity="%g" fill="%s" stroke="%s">%s</g>`+"\n",
			s.Motif.Opacity, motifFill, motifFill, s.Motif.SVG)
	}

	for i, l := range s.Layers {
		d, bb, err := wordPath(l.Font, l.Text)
		if err != nil {
			return "", fmt.Errorf("layer %d: %w", i, err)
		}
		fill := l.Fill
		if fill == "hero" {
			fill = "url(#hero)"
		}
		fmt.Fprintf(&b, `  <g transform="%s"><path d="%s" fill="%s"/></g>`+"\n",
			transformFor(bb, l.Height, l.CenterX, l.Y, l.Align), d, fill)
	}

	b.WriteString("</svg>\n")
	return b.String(), nil
}
